### ISSUE TITLE
Class 'dmstr\web\AdminLteAsset' not found

### ISSUE THREAD

**Issue by racielbd** [dmstr/yii2-adminlte-asset#105] opened 2017-02-06 21:11 UTC
Hi I'm trying to use this theme with yii2 advanced but its not working....
I'm not working with composer so i download the code from here and put the files under vendor/dmsrt/...
I configured like the readme say in the config file and this site
```
'components' => [
    'view' => [
         'theme' => [
             'pathMap' => [
                '@app/views' => '@vendor/dmstr/yii2-adminlte-asset/example-views/yiisoft/yii2-app'
             ],
         ],
    ],
],
```

the path of the views its ok, but when i run the index page get the error (**Class 'dmstr\web\AdminLteAsset' not found**) and not matter where i copy the files it doesn't work

can someone help me....

**Comment by githubjeka** [comment] 2017-02-07 06:03
Error in this row https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/main.php#L25

This file is required https://github.com/dmstr/yii2-adminlte-asset/blob/master/web/AdminLteAsset.php

reinstall yii2-adminlte-asset via composer

**Comment by mlordelo** [comment] 2017-05-05 01:49
I got the same error. I tried to reinstall and the composer uninstalled Yii2 packages, causing other errors.

AdminLteAsset.php exists in vendor/dmstr/web.

**Comment by githubjeka** [comment] 2017-05-05 04:50
reinstall yii2-adminlte-asset
reinstall yii2-adminlte-asset
reinstall yii2-adminlte-asset
reinstall yii2-adminlte-asset
reinstall yii2-adminlte-asset

again and again, this file can not fail to be.

**Comment by schmunk42** [comment] 2017-05-05 12:12
Looks like this is some kind of autoloading issue.

> AdminLteAsset.php exists in vendor/dmstr/web.

@mlordelo Really?! I wonder how it gets there, it should be in `vendor/dmstr/yii2-adminlte-asset/web/`

If installing manually an alias like `'@dmstr/web' => '@vendor/dmstr/yii2-adminlte-asset/web/'` could help, but is not recommended.

**Comment by mlordelo** [comment] 2017-05-05 14:35
I downloaded Yii2 Advanced again, extracted and instaled  AdminLTE, and its works. 

I observed that the folder strutcture was diferent. In my "broken" version there was a folder "_protected", witch does not exists in the new instalattion. I don't know if this is a problem.

Besides, when I tried to reinstall via composer, I was running the command in backend folder, not in root folder.

**Comment by schmunk42** [comment] 2017-05-05 16:13
Closing then, please reopen or comment if there's still an issue.

**Closed by schmunk42** 2017-05-05 16:13 UTC

**Comment by a-salihov** [comment] 2019-12-26 19:51
I have the same error "Class 'dmstr\web\AdminLteAsset' not found" in the same situation (there is no way to use composer on some hosting).

If I apply the answer: "If installing manually an alias like '@dmstr/web' => '@vendor/dmstr/yii2-adminlte-asset/web/' could help, but is not recommended." then I get another error:

"Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "rmrevin\yii\fontawesome\AssetBundle".
↵
Caused by: ReflectionException
Class rmrevin\yii\fontawesome\AssetBundle does not exist in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 447"

What can help in this case?

**Comment by githubjeka** [comment] 2019-12-27 05:14
try to use master branch code.
Class `rmrevin\yii\fontawesome\AssetBundle` removed from source. You use old version of code.

**Comment by schmunk42** [comment] 2019-12-27 08:32
@a-salihov Did you install via composer, which version do you have?

**Comment by a-salihov** [comment] 2019-12-27 12:03
> Did you install via composer, which version do you have?

Yes, I did. I installed AdminLteAsset on my local computer via composer.
Composer shows version: dmstr/yii2-adminlte-asset          2.6.2
Locally everything works fine. But when I deployed the projects to the hosting just copying, I got that error.

**Comment by punjabideveloper** [comment] 2020-05-11 05:29
> > Did you install via composer, which version do you have?
> 
> Yes, I did. I installed AdminLteAsset on my local computer via composer.
> Composer shows version: dmstr/yii2-adminlte-asset 2.6.2
> Locally everything works fine. But when I deployed the projects to the hosting just copying, I got that error.

You need to run composer on your server too where you are running your project.
