### ISSUE TITLE
Problems with IE 11, Yii2 and AdminLTE

### ISSUE THREAD

**Issue by eothein** [dmstr/yii2-adminlte-asset#51] opened 2015-06-02 19:57 UTC
Dear all

First and foremost, good work on the template! I just have one issue, which I cannot seem to resolve: my layout gets all messed up in IE 11. Do you have the same problems?

Kind regards

**Comment by schmunk42** [comment] 2015-06-02 20:26
From: https://github.com/almasaeed2010/AdminLTE/issues/462
Check your asset manager settings and retry with a clean setup.

I also don't have IE available for testing.

CC: @githubjeka

**Comment by githubjeka** [comment] 2015-06-03 05:06
Screenshot has been made from IE11, on Readme.md

![image](https://cloud.githubusercontent.com/assets/874234/7953007/d974fd52-09c6-11e5-9c7d-2d2aa8fe4f20.png)

I don't see any problems. Perhaps you have forgotten to close tag somewhere . Chrome and other browsers is forgiven, and IE break everything.

Check it https://validator.w3.org/#validate_by_input

**Comment by schmunk42** [comment] 2015-06-18 13:04
@eothein We've encountered similar problems with IE 10 on a client's computer.
Which "compatibility-mode" do you habe set in IE 10? And could you post some screenshots?

**Comment by PreetSaxena** [comment] 2015-12-02 11:00
Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: dektrium\user\models\User::confirmed_at

occuring during login

**Comment by githubjeka** [comment] 2015-12-02 11:03
@PreetSaxena see **your**  the `dektrium\user\models\User` model. It isn't `yii2-adminlte-asset` issue

**Comment by schmunk42** [comment] 2015-12-04 17:39
@eothein @PreetSaxena Is this still an issue or can we close this?

**Comment by schmunk42** [comment] 2015-12-13 20:55
Closed, due to inactivity, please reopen or create a new one, if there are still problems.

**Closed by schmunk42** 2015-12-13 20:55 UTC
Labels: help wanted
